from .flatten_dict import flatten_dict
from .compute_fairness_from_df import add_fairness_metrics_by_emotion
from .plot import plot_fairness_vs_hparam, plot_fairness_by_emotion
from .figure_collector import FigureCollector